'use client'
import type { CoverLetter } from '@/types/europass'

interface CoverLetterPreviewProps {
  letter: CoverLetter
  printRef?: React.RefObject<HTMLDivElement | null>
}

function Flag() {
  return (
    <svg width="28" height="20" viewBox="0 0 32 22" xmlns="http://www.w3.org/2000/svg">
      <rect width="32" height="22" fill="#003399" />
      {[...Array(12)].map((_, i) => {
        const a = (i * 30 - 90) * (Math.PI / 180)
        const cx = 16 + 7 * Math.cos(a), cy = 11 + 7 * Math.sin(a)
        return (
          <polygon key={i}
            points={`${cx},${cy-2} ${cx+0.8},${cy-0.7} ${cx+1.4},${cy+1.7} ${cx},${cy+0.9} ${cx-1.4},${cy+1.7} ${cx-0.8},${cy-0.7}`}
            fill="#FFCC00" />
        )
      })}
    </svg>
  )
}

export default function CoverLetterPreview({ letter: l, printRef }: CoverLetterPreviewProps) {
  return (
    <div
      ref={printRef as React.RefObject<HTMLDivElement>}
      className="europass-doc"
      style={{
        background: 'white', color: '#1a1a2e',
        fontFamily: '"DM Sans", Arial, sans-serif',
        fontSize: 11, lineHeight: 1.7,
        maxWidth: 794, margin: '0 auto',
        padding: '48px 56px',
        boxShadow: '0 4px 48px rgba(0,0,0,0.4)',
        borderRadius: 4,
        minHeight: 1000,
      }}
    >
      {/* EU Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28, borderBottom: '3px solid #003399', paddingBottom: 14 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Flag />
          <span style={{ fontSize: 9, color: '#6b7280', letterSpacing: '0.08em', textTransform: 'uppercase', lineHeight: 1.4 }}>
            Europass<br />Cover Letter
          </span>
        </div>
        <div style={{ textAlign: 'right', fontSize: 11, color: '#374151' }}>
          <div style={{ fontWeight: 600 }}>{l.senderName}</div>
          <div style={{ color: '#6b7280' }}>{l.senderTitle}</div>
          <div style={{ color: '#6b7280' }}>{l.senderEmail}</div>
          <div style={{ color: '#6b7280' }}>{l.senderPhone}</div>
        </div>
      </div>

      {/* Recipient block */}
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontWeight: 600 }}>{l.recipientName || 'Hiring Manager'}</div>
        {l.recipientTitle && <div style={{ color: '#6b7280' }}>{l.recipientTitle}</div>}
        <div style={{ fontWeight: 600, marginTop: 4 }}>{l.company}</div>
        {l.companyAddress && <div style={{ color: '#6b7280' }}>{l.companyAddress}</div>}
      </div>

      {/* Date */}
      <div style={{ marginBottom: 20, color: '#6b7280', fontSize: 10.5 }}>{l.date}</div>

      {/* Subject */}
      <div style={{
        fontWeight: 700, fontSize: 12, color: '#003399',
        marginBottom: 20, paddingBottom: 8,
        borderBottom: '1px solid #e5e7eb',
      }}>
        Re: {l.subject}
      </div>

      {/* Salutation */}
      <p style={{ marginBottom: 14, fontWeight: 500 }}>{l.salutation}</p>

      {/* Opening */}
      <p style={{ marginBottom: 14, textAlign: 'justify' }}>{l.opening}</p>

      {/* Body paragraphs */}
      {l.body?.map((para, i) => (
        <p key={i} style={{ marginBottom: 14, textAlign: 'justify' }}>{para}</p>
      ))}

      {/* Closing */}
      <p style={{ marginBottom: 32, textAlign: 'justify' }}>{l.closing}</p>

      {/* Sign-off */}
      <div style={{ marginBottom: 48 }}>{l.signoff}</div>

      {/* Signature block */}
      <div style={{ borderTop: '1px solid #e5e7eb', paddingTop: 12 }}>
        <div style={{ fontWeight: 700, fontSize: 12 }}>{l.senderName}</div>
        <div style={{ color: '#6b7280', fontSize: 10.5 }}>{l.senderTitle}</div>
        <div style={{ color: '#003399', fontSize: 10.5 }}>{l.senderEmail}</div>
      </div>

      {/* Footer */}
      <div style={{ marginTop: 40, borderTop: '1px solid #e5e7eb', paddingTop: 10, fontSize: 9, color: '#9ca3af', display: 'flex', justifyContent: 'space-between' }}>
        <span>© European Union, 2002-{new Date().getFullYear()} · europass.eu</span>
        <span>Generated by PradipBuild</span>
      </div>
    </div>
  )
}
